###########################################################
### Welcome to Beautiful Jekyll!
### This config file is meant for settings that affect your entire website. When you first
### set up your website you should go through all these settings and edit them, but after
### the initial set up you won't need to come back to this file often.
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: SOB25 - Shopstr Development Blog

# Your name to show in the footer
author: Nitish Jha

# Short description of your site
description: "Summer of Bitcoin 2025 project Blog - Building non-custodial payment infrastructure for Shopstr"

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About: "about"
  Projects:
    - Shopstr Payment Layer: "#"
    - SOB25 Portfolio: "https://github.com/Nj221102"
  Resources:
    - Shopstr: "https://shopstr.store"
    - Bitcoin Lightning: "https://lightning.network"

################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/avatar-icon.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image


#####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# You can change the order that they show up on the page by changing the order here.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "nitishj221102@gmail.com"
  github: Nj221102
  linkedin: nitish-jha-2b82aa155
  rss: true

# GitHub Pages configuration
url: "https://nj221102.github.io"
baseurl: "/Nitish-project-blogs"
repository: "Nj221102/Nitish-project-blogs"

# SEO and metadata
title-separator: " | "
description: "SOB25 project updates: Building Bitcoin Lightning payment infrastructure for Shopstr. Technical insights, development progress, and blockchain innovation."
keywords: "Bitcoin, Lightning Network, SOB25, Shopstr, Payments, Blockchain, Summer of Bitcoin"

# RSS feed description
rss-description: "SOB25 project updates: Building Bitcoin Lightning payment infrastructure for Shopstr. Technical insights, development progress, and blockchain innovation."

# GitHub Pages optimization
github_username: Nj221102
author:
  name: "Nitish Jha"
  email: "nitishj221102@gmail.com"
  github: "Nj221102"
  linkedin: "nitish-jha-2b82aa155"

# SOB25 Bitcoin-inspired theme colors
page-col: "#FAFAFA"
text-col: "#2C3E50"
link-col: "#F7931A"
hover-col: "#E67E22"
navbar-col: "#FFFFFF"
navbar-text-col: "#2C3E50"
navbar-border-col: "#E8E8E8"
footer-col: "#34495E"
footer-text-col: "#BDC3C7"
footer-link-col: "#ECF0F1"
footer-hover-col: "#F7931A"

# Custom fonts and typography
google_fonts: "Roboto:300,400,500,700|Source+Code+Pro:400,700"

# GitHub Pages Jekyll settings
remote_theme: "daattali/beautiful-jekyll@6.0.1"

# Exclude files from GitHub Pages build
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor/
  - .bundle/
  - .git/
  - .github/
  - node_modules/
  - "*.gemspec"
  - "*.gem"

###########################
# --- General options --- #
###########################

# Modern Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 8
timezone: "UTC"

# Disable Sass to avoid compatibility issues
sass:
  load_paths:
    - _sass
  style: :compressed

# SEO and sharing
share-links-active:
  twitter: true
  linkedin: true
  facebook: false

# Site features
post_search: true
feed_show_excerpt: true
feed_show_tags: true
excerpt_length: 75

# Modern kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Jekyll plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Default YAML values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
      show-avatar: true
  - scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true

# Build settings
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Appraisals
  - staticman.yml
  - vendor/
  - .bundle/
  - .git/
  - .github/
  - node_modules/

# SOB25 specific settings
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Site verification and analytics (add your own)
# google_analytics: "G-XXXXXXXXXX"
# google_site_verification: "your-verification-code"

